(() => {
  const q=s=>document.querySelector(s);
  const content=()=>document.getElementById('content');
  const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
  const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const toast=t=>window.showToast?window.showToast(t):alert(t);
  const setHead=(title,sub)=>{const a=q('#pageTitle'),b=q('#pageSubtitle');if(a)a.textContent=title;if(b)b.textContent=sub};
  const KEY='aii-collaborations';

  const style=document.createElement('style');
  style.textContent=`
    .collab-grid{display:grid;grid-template-columns:minmax(340px,.9fr) minmax(440px,1.1fr);gap:14px}.collab-card{background:#fff;border:1px solid #e7e9f1;border-radius:16px;padding:18px}.collab-form{display:grid;gap:10px}.collab-form label{display:grid;gap:5px;font-size:9px;font-weight:800;color:#717887}.collab-form input,.collab-form textarea,.collab-form select{width:100%;box-sizing:border-box;border:1px solid #dfe2eb;border-radius:10px;padding:10px 11px;background:#fbfbfd;color:#242833;font:inherit}.collab-form textarea{min-height:90px;resize:vertical}.collab-two{display:grid;grid-template-columns:1fr 1fr;gap:9px}.collab-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.collab-list{display:grid;gap:8px}.collab-item{border:1px solid #e6e8ef;border-radius:12px;padding:12px;background:#fff;cursor:pointer}.collab-item:hover{border-color:#cabdfa}.collab-item-head{display:flex;justify-content:space-between;gap:10px}.collab-item b{font-size:10px}.collab-item small{font-size:8px;color:#7d8491}.collab-badges{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.collab-badge{padding:5px 7px;border-radius:999px;background:#f1edff;color:#6647da;font-size:7px;font-weight:900}.collab-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:12px}.collab-kpi{border:1px solid #eceef5;border-radius:12px;padding:11px;background:#fafafe}.collab-kpi b{display:block;font-size:17px}.collab-kpi span{font-size:8px;color:#7b8290}.collab-empty{padding:30px;text-align:center;color:#8a909b;border:1px dashed #d9ddea;border-radius:12px}.collab-note{font-size:8px;color:#7d8491;margin-top:8px}@media(max-width:950px){.collab-grid,.collab-two,.collab-kpis{grid-template-columns:1fr}}
  `;document.head.appendChild(style);

  const all=()=>read(KEY,[]);
  const write=items=>{save(KEY,items);document.dispatchEvent(new CustomEvent('aii:collabs-changed',{detail:{count:items.length}}));};
  const money=v=>{const n=Number(v||0);return Number.isFinite(n)?`${n.toLocaleString('pl-PL')} zł`:'0 zł'};

  function render(){
    setHead('Współprace','Baza marek, ofert, terminów i historii kontaktu.');
    const items=all();
    const active=items.filter(x=>!['Zakończona','Odrzucona'].includes(x.status)).length;
    const paid=items.filter(x=>x.type==='Płatna').reduce((s,x)=>s+Number(x.value||0),0);
    const waiting=items.filter(x=>['Oferta wysłana','Oczekiwanie na odpowiedź'].includes(x.status)).length;
    const barter=items.filter(x=>x.type==='Barter').length;
    content().innerHTML=`<section class="creator-tool-hero"><div><div class="eyebrow">BRAND CRM</div><h2>Współprace</h2><p>Zarządzaj kontaktami z markami, ofertami, barterami, stawkami i terminami odpowiedzi.</p></div><span class="tag">CRM</span></section><section class="collab-kpis"><div class="collab-kpi"><b>${active}</b><span>aktywne</span></div><div class="collab-kpi"><b>${waiting}</b><span>czeka na odpowiedź</span></div><div class="collab-kpi"><b>${barter}</b><span>bartery</span></div><div class="collab-kpi"><b>${money(paid)}</b><span>wartość płatnych</span></div></section><section class="collab-grid"><div class="collab-card"><h3>Nowa / edytowana współpraca</h3><div class="collab-form"><label>Marka<input id="coBrand" placeholder="Nazwa marki"></label><div class="collab-two"><label>Typ<select id="coType"><option>Płatna</option><option>Barter</option><option>Ambasadorstwo</option><option>Affiliate</option></select></label><label>Status<select id="coStatus"><option>Nowy kontakt</option><option>Oferta wysłana</option><option>Oczekiwanie na odpowiedź</option><option>Negocjacje</option><option>Zaakceptowana</option><option>Realizacja</option><option>Do rozliczenia</option><option>Zakończona</option><option>Odrzucona</option></select></label></div><div class="collab-two"><label>Wartość / stawka<input id="coValue" type="number" min="0" step="50" placeholder="0"></label><label>Termin odpowiedzi<input id="coReply" type="date"></label></div><div class="collab-two"><label>Kontakt / e-mail<input id="coContact" placeholder="osoba@marka.pl"></label><label>Deadline realizacji<input id="coDeadline" type="date"></label></div><label>Zakres współpracy<textarea id="coScope" placeholder="Np. 1 Reels, 3 Stories, 2 zdjęcia..."></textarea></label><label>Historia / notatki<textarea id="coNotes" placeholder="Ustalenia, odpowiedzi, negocjacje, ważne informacje..."></textarea></label></div><input id="coId" type="hidden"><div class="collab-actions"><button class="primary" id="coSave">Zapisz współpracę</button><button class="ghost" id="coClear">Wyczyść</button><button class="ghost" id="coDelete">Usuń</button></div><div class="collab-note">Dane są zapisywane lokalnie i działają także bez AI.</div></div><div class="collab-card"><h3>Baza współprac</h3><div class="collab-list" id="coList">${items.length?items.map((x,i)=>`<div class="collab-item" data-co="${i}"><div class="collab-item-head"><b>${esc(x.brand)}</b><small>${esc(x.replyDate||x.deadline||'bez terminu')}</small></div><div class="collab-badges"><span class="collab-badge">${esc(x.type)}</span><span class="collab-badge">${esc(x.status)}</span><span class="collab-badge">${money(x.value)}</span></div><small>${esc(x.scope||'Brak zakresu')}</small></div>`).join(''):'<div class="collab-empty">Brak zapisanych współprac.</div>'}</div></div></section>`;

    const clear=()=>{['coBrand','coValue','coReply','coContact','coDeadline','coScope','coNotes','coId'].forEach(id=>q('#'+id).value='');q('#coType').value='Płatna';q('#coStatus').value='Nowy kontakt';};
    q('#coClear').onclick=clear;
    q('#coSave').onclick=()=>{const brand=q('#coBrand').value.trim();if(!brand)return toast('Wpisz nazwę marki');const list=all();const item={brand,type:q('#coType').value,status:q('#coStatus').value,value:Number(q('#coValue').value||0),replyDate:q('#coReply').value,contact:q('#coContact').value.trim(),deadline:q('#coDeadline').value,scope:q('#coScope').value.trim(),notes:q('#coNotes').value.trim(),updatedAt:Date.now()};const id=q('#coId').value;if(id!=='')list[Number(id)]=item;else list.unshift(item);write(list);toast('Współpraca zapisana');render();};
    q('#coDelete').onclick=()=>{const id=q('#coId').value;if(id==='')return toast('Wybierz współpracę z listy');const list=all();list.splice(Number(id),1);write(list);toast('Współpraca usunięta');render();};
    document.querySelectorAll('[data-co]').forEach(el=>el.onclick=()=>{const i=Number(el.dataset.co),x=all()[i];if(!x)return;q('#coId').value=i;q('#coBrand').value=x.brand||'';q('#coType').value=x.type||'Płatna';q('#coStatus').value=x.status||'Nowy kontakt';q('#coValue').value=x.value||'';q('#coReply').value=x.replyDate||'';q('#coContact').value=x.contact||'';q('#coDeadline').value=x.deadline||'';q('#coScope').value=x.scope||'';q('#coNotes').value=x.notes||'';toast('Wczytano współpracę');});
  }

  function bind(){document.querySelectorAll('.nav-item[data-view="collabs"]').forEach(a=>{if(a.dataset.collabBound)return;a.dataset.collabBound='1';a.addEventListener('click',()=>setTimeout(()=>{render();localStorage.setItem('aii-last-view','collabs')},20));});}
  document.addEventListener('DOMContentLoaded',()=>{bind();if(localStorage.getItem('aii-last-view')==='collabs')setTimeout(render,90);const nav=document.querySelector('.nav');if(nav)new MutationObserver(bind).observe(nav,{childList:true,subtree:true});});
})();