(() => {
  const q=s=>document.querySelector(s);
  const content=()=>document.getElementById('content');
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
  const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const toast=t=>window.showToast?window.showToast(t):alert(t);
  const setHead=(title,sub)=>{const a=q('#pageTitle'),b=q('#pageSubtitle');if(a)a.textContent=title;if(b)b.textContent=sub};

  const style=document.createElement('style');
  style.textContent=`
    .suite-grid{display:grid;grid-template-columns:minmax(320px,.92fr) minmax(360px,1.08fr);gap:14px}.suite-card{background:#fff;border:1px solid #e7e9f1;border-radius:16px;padding:18px}.suite-card h3{margin:0 0 12px}.suite-form{display:grid;gap:10px}.suite-form label{display:grid;gap:5px;font-size:9px;font-weight:800;color:#717887}.suite-form input,.suite-form textarea,.suite-form select{width:100%;box-sizing:border-box;border:1px solid #dfe2eb;border-radius:10px;padding:10px 11px;background:#fbfbfd;color:#242833;font:inherit}.suite-form textarea{min-height:88px;resize:vertical}.suite-two{display:grid;grid-template-columns:1fr 1fr;gap:9px}.suite-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.suite-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:12px 0}.suite-kpi{padding:12px;border:1px solid #eceef5;border-radius:12px;background:#fafafe}.suite-kpi b{display:block;font-size:18px}.suite-kpi span{font-size:8px;color:#7b8290}.suite-preview{min-height:360px;border-radius:16px;border:1px solid #e4e6ef;background:linear-gradient(145deg,#171925,#6d4be8 58%,#d8ceff);display:grid;place-items:center;overflow:hidden;position:relative}.suite-preview img{width:100%;height:100%;object-fit:cover}.suite-avatar-mark{width:150px;height:150px;border-radius:50%;background:rgba(255,255,255,.14);border:1px solid rgba(255,255,255,.35);display:grid;place-items:center;font-size:48px;font-weight:900;color:white;backdrop-filter:blur(10px)}.suite-note{font-size:8px;color:#7d8491;line-height:1.55;margin-top:10px}.suite-status{display:inline-flex;align-items:center;gap:6px;padding:5px 8px;border-radius:999px;background:#f1edff;color:#6647da;font-size:8px;font-weight:900}.suite-pills{display:flex;gap:6px;flex-wrap:wrap}.suite-pill{padding:7px 9px;border:1px solid #e4e6ef;border-radius:999px;background:#fff;font-size:8px}.suite-swatch{height:72px;border-radius:12px;border:1px solid #e5e7ef;display:flex;align-items:end;padding:9px;font-weight:800;font-size:8px}.suite-output{white-space:pre-wrap;line-height:1.55;background:#fafafe;border:1px dashed #d9ddea;border-radius:12px;padding:13px;min-height:120px;font-size:9px}@media(max-width:900px){.suite-grid,.suite-two,.suite-kpis{grid-template-columns:1fr}}
  `;
  document.head.appendChild(style);

  function avatarStudio(){
    setHead('AI Avatar','Zbuduj spójną cyfrową personę do zdjęć i kampanii.');
    const dna=read('aii-avatar-dna',{name:'Nova',age:'28–35',hair:'ciemny blond, delikatne fale',eyes:'zielone',style:'premium beauty + natural UGC',traits:'ciepła, pewna siebie, autentyczna',signature:'miękkie światło, jasne neutralne tło'});
    content().innerHTML=`<section class="creator-tool-hero"><div><div class="eyebrow">IDENTITY ENGINE</div><h2>AI Avatar Studio</h2><p>Zapisz Avatar DNA raz i wykorzystuj je we wszystkich kolejnych zdjęciach.</p></div><span class="tag">CONSISTENCY MODE</span></section><section class="suite-grid"><div class="suite-card"><span class="suite-status">● AVATAR DNA</span><div class="suite-form" style="margin-top:12px"><label>Nazwa avatara<input id="avName" value="${esc(dna.name)}"></label><div class="suite-two"><label>Wiek wizualny<input id="avAge" value="${esc(dna.age)}"></label><label>Oczy<input id="avEyes" value="${esc(dna.eyes)}"></label></div><label>Włosy<input id="avHair" value="${esc(dna.hair)}"></label><label>Styl<select id="avStyle"><option>Premium beauty + natural UGC</option><option>Luxury editorial</option><option>Soft lifestyle</option><option>Minimal studio</option></select></label><label>Cechy osobowości<input id="avTraits" value="${esc(dna.traits)}"></label><label>Stały podpis wizualny<input id="avSignature" value="${esc(dna.signature)}"></label><label>Scena testowa<textarea id="avScene" placeholder="Np. beauty creator przy jasnej toaletce, trzyma serum, miękkie światło dzienne"></textarea></label></div><div class="suite-actions"><button class="primary" id="avSave">Zapisz Avatar DNA</button><button class="ghost" id="avGenerate">Generuj test avatara</button></div><div class="suite-note">Avatar DNA jest przechowywane lokalnie. Zdjęcie testowe korzysta z tego samego bezpiecznego backendu co Generator zdjęć; przy jego braku aplikacja pozostaje użyteczna.</div></div><div class="suite-card"><div class="suite-kpis"><div class="suite-kpi"><b id="avConsistency">96%</b><span>spójność DNA</span></div><div class="suite-kpi"><b>6</b><span>cech stałych</span></div><div class="suite-kpi"><b>4:5</b><span>format testu</span></div></div><div class="suite-preview" id="avPreview"><div class="suite-avatar-mark">AI</div></div><div class="suite-output" id="avPrompt" style="margin-top:10px">Zapisz DNA i wygeneruj scenę testową.</div></div></section>`;
    q('#avStyle').value=dna.style||'Premium beauty + natural UGC';
    const get=()=>({name:q('#avName').value.trim(),age:q('#avAge').value.trim(),hair:q('#avHair').value.trim(),eyes:q('#avEyes').value.trim(),style:q('#avStyle').value,traits:q('#avTraits').value.trim(),signature:q('#avSignature').value.trim()});
    const prompt=()=>{const d=get(),scene=q('#avScene').value.trim()||'professional beauty creator portrait in a bright premium studio';return `Create a photorealistic recurring AI influencer named ${d.name}. Visual age: ${d.age}. Hair: ${d.hair}. Eyes: ${d.eyes}. Personal style: ${d.style}. Personality expressed visually: ${d.traits}. Signature visual language: ${d.signature}. Scene: ${scene}. Keep facial identity, proportions, hair color, eye color and overall appearance consistent across generations. Natural skin texture, realistic hands, commercial photography, no watermark, no text.`};
    q('#avSave').onclick=()=>{save('aii-avatar-dna',get());q('#avConsistency').textContent='100%';toast('Avatar DNA zapisane')};
    q('#avGenerate').onclick=async()=>{const p=prompt();q('#avPrompt').textContent=p;save('aii-avatar-dna',get());const b=q('#avGenerate'),preview=q('#avPreview');b.disabled=true;b.textContent='Generuję…';preview.innerHTML='<span style="color:white">Generowanie testu avatara…</span>';try{const r=await fetch('https://ai-influencer-studio-api.vercel.app/api/generate-image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:p,format:'4:5'})});const data=await r.json().catch(()=>({}));if(!r.ok||!data.image)throw new Error(data.error||`Błąd API ${r.status}`);preview.innerHTML=`<img alt="AI Avatar" src="${data.image}">`;toast('Avatar testowy wygenerowany')}catch(e){preview.innerHTML='<div class="suite-avatar-mark">AI</div>';q('#avPrompt').textContent=p+'\n\nBackend AI chwilowo niedostępny: '+String(e.message||e);toast('Zapisano prompt avatara — backend jeszcze niedostępny')}finally{b.disabled=false;b.textContent='Generuj test avatara'}};
  }

  function profileStudio(){
    setHead('Profil i wizerunek','Centralne ustawienia persony twórczej.');
    const p=read('aii-creator-profile',{name:'Karolina',niche:'Beauty / UGC / lifestyle',tone:'naturalny, konkretny, lekko premium',bio:'Tworzę estetyczne treści, testy produktów i materiały UGC.',audience:'kobiety 25–44, zainteresowane beauty i świadomymi zakupami'});
    content().innerHTML=`<section class="creator-tool-hero"><div><div class="eyebrow">CREATOR IDENTITY</div><h2>Profil i wizerunek</h2><p>Jedno źródło danych dla postów, kampanii, avatara i materiałów AI.</p></div><span class="tag">MASTER PROFILE</span></section><section class="suite-grid"><div class="suite-card"><div class="suite-form"><label>Nazwa twórcy<input id="pfName" value="${esc(p.name)}"></label><label>Nisza<input id="pfNiche" value="${esc(p.niche)}"></label><label>Ton komunikacji<input id="pfTone" value="${esc(p.tone)}"></label><label>Bio<textarea id="pfBio">${esc(p.bio)}</textarea></label><label>Główna grupa odbiorców<textarea id="pfAudience">${esc(p.audience)}</textarea></label></div><div class="suite-actions"><button class="primary" id="pfSave">Zapisz profil</button></div></div><div class="suite-card"><h3>Creator DNA</h3><div class="suite-pills"><span class="suite-pill">Spójny ton</span><span class="suite-pill">UGC ready</span><span class="suite-pill">Brand-safe</span><span class="suite-pill">Multi-platform</span></div><div class="suite-output" id="pfSummary" style="margin-top:12px">${esc(p.name)} • ${esc(p.niche)}\n\n${esc(p.bio)}\n\nOdbiorcy: ${esc(p.audience)}</div></div></section>`;
    q('#pfSave').onclick=()=>{const v={name:q('#pfName').value.trim(),niche:q('#pfNiche').value.trim(),tone:q('#pfTone').value.trim(),bio:q('#pfBio').value.trim(),audience:q('#pfAudience').value.trim()};save('aii-creator-profile',v);q('#pfSummary').textContent=`${v.name} • ${v.niche}\n\n${v.bio}\n\nOdbiorcy: ${v.audience}`;toast('Profil twórcy zapisany')};
  }

  function voiceStudio(){
    setHead('Głos AI','Przygotuj Voice DNA i skrypty do syntezy mowy.');
    const v=read('aii-voice-dna',{language:'Polski',pace:'Naturalne',emotion:'Ciepła pewność siebie',notes:'wyraźna dykcja, naturalne pauzy, bez radiowego przerysowania'});
    content().innerHTML=`<section class="creator-tool-hero"><div><div class="eyebrow">VOICE LAB</div><h2>Głos AI</h2><p>Definiuj brzmienie, tempo i emocję dla przyszłych nagrań.</p></div><span class="tag">VOICE DNA</span></section><section class="suite-grid"><div class="suite-card"><div class="suite-form"><div class="suite-two"><label>Język<select id="vcLang"><option>Polski</option><option>English</option><option>Deutsch</option></select></label><label>Tempo<select id="vcPace"><option>Naturalne</option><option>Spokojne</option><option>Dynamiczne</option></select></label></div><label>Emocja<input id="vcEmotion" value="${esc(v.emotion)}"></label><label>Charakter głosu<textarea id="vcNotes">${esc(v.notes)}</textarea></label><label>Tekst próbny<textarea id="vcScript" placeholder="Wpisz tekst do próbki głosowej..."></textarea></label></div><div class="suite-actions"><button class="primary" id="vcSave">Zapisz Voice DNA</button><button class="ghost" id="vcPrep">Przygotuj skrypt lektorski</button></div></div><div class="suite-card"><h3>Skrypt gotowy do TTS</h3><div class="suite-output" id="vcOut">Wpisz tekst próbny i przygotuj wersję lektorską.</div><div class="suite-note">Synteza audio zostanie podłączona jako osobny bezpieczny backend. Ten moduł już zapisuje ustawienia i przygotowuje tekst bez blokowania aplikacji.</div></div></section>`;
    q('#vcLang').value=v.language;q('#vcPace').value=v.pace;
    q('#vcSave').onclick=()=>{save('aii-voice-dna',{language:q('#vcLang').value,pace:q('#vcPace').value,emotion:q('#vcEmotion').value.trim(),notes:q('#vcNotes').value.trim()});toast('Voice DNA zapisane')};
    q('#vcPrep').onclick=()=>{const text=q('#vcScript').value.trim()||'Cześć! To jest próbka mojego głosu AI.';q('#vcOut').textContent=`[Język: ${q('#vcLang').value}] [Tempo: ${q('#vcPace').value}] [Emocja: ${q('#vcEmotion').value}]\n\n${text.replace(/([.!?])\s+/g,'$1\n\n')}`;toast('Skrypt lektorski przygotowany')};
  }

  function brandStudio(){
    setHead('Marka osobista','Kolory, styl i zasady komunikacji marki.');
    const b=read('aii-brand-kit',{primary:'#6d4be8',secondary:'#171925',accent:'#d8ceff',keywords:'premium, autentycznie, nowocześnie, kobieco'});
    content().innerHTML=`<section class="creator-tool-hero"><div><div class="eyebrow">BRAND SYSTEM</div><h2>Marka osobista</h2><p>Ustal spójne zasady wizualne dla całej aplikacji.</p></div><span class="tag">BRAND KIT</span></section><section class="suite-grid"><div class="suite-card"><div class="suite-form"><div class="suite-two"><label>Kolor główny<input id="brPrimary" type="color" value="${esc(b.primary)}"></label><label>Kolor ciemny<input id="brSecondary" type="color" value="${esc(b.secondary)}"></label></div><label>Kolor akcentu<input id="brAccent" type="color" value="${esc(b.accent)}"></label><label>Słowa marki<textarea id="brKeywords">${esc(b.keywords)}</textarea></label></div><div class="suite-actions"><button class="primary" id="brSave">Zapisz Brand Kit</button></div></div><div class="suite-card"><h3>Podgląd palety</h3><div class="suite-two"><div class="suite-swatch" id="sw1" style="background:${esc(b.primary)};color:white">PRIMARY</div><div class="suite-swatch" id="sw2" style="background:${esc(b.secondary)};color:white">DARK</div></div><div class="suite-swatch" id="sw3" style="margin-top:9px;background:${esc(b.accent)}">ACCENT</div><div class="suite-output" id="brOut" style="margin-top:10px">${esc(b.keywords)}</div></div></section>`;
    const refresh=()=>{q('#sw1').style.background=q('#brPrimary').value;q('#sw2').style.background=q('#brSecondary').value;q('#sw3').style.background=q('#brAccent').value};['#brPrimary','#brSecondary','#brAccent'].forEach(s=>q(s).oninput=refresh);
    q('#brSave').onclick=()=>{const v={primary:q('#brPrimary').value,secondary:q('#brSecondary').value,accent:q('#brAccent').value,keywords:q('#brKeywords').value.trim()};save('aii-brand-kit',v);q('#brOut').textContent=v.keywords;toast('Brand Kit zapisany')};
  }

  function stylesStudio(){
    setHead('Szablony stylu','Gotowe presety do zdjęć i treści.');
    content().innerHTML=`<section class="creator-tool-hero"><div><div class="eyebrow">STYLE LIBRARY</div><h2>Szablony stylu</h2><p>Wybierz preset i ustaw go jako domyślny dla generatorów.</p></div></section><section class="suite-card"><div class="suite-two"><button class="suite-swatch" data-style="Beauty premium" style="background:linear-gradient(135deg,#f4eaff,#fff)">Beauty premium</button><button class="suite-swatch" data-style="UGC natural" style="background:linear-gradient(135deg,#efe9df,#fff)">UGC natural</button><button class="suite-swatch" data-style="Luxury editorial" style="background:linear-gradient(135deg,#151515,#777);color:white">Luxury editorial</button><button class="suite-swatch" data-style="Minimal studio" style="background:linear-gradient(135deg,#f3f3f3,#d7d7d7)">Minimal studio</button></div><div class="suite-output" id="stOut" style="margin-top:12px">Domyślny styl: ${esc(localStorage.getItem('aii-default-style')||'Beauty premium')}</div></section>`;
    document.querySelectorAll('[data-style]').forEach(b=>b.onclick=()=>{localStorage.setItem('aii-default-style',b.dataset.style);q('#stOut').textContent='Domyślny styl: '+b.dataset.style;toast('Styl ustawiony jako domyślny')});
  }

  const handlers={profile:profileStudio,avatar:avatarStudio,'ai-avatar':avatarStudio,voice:voiceStudio,brand:brandStudio,styles:stylesStudio};
  function bind(){document.querySelectorAll('.nav-item[data-view]').forEach(a=>{const k=a.dataset.view;if(!handlers[k]||a.dataset.suiteBound)return;a.dataset.suiteBound='1';a.addEventListener('click',()=>setTimeout(()=>{handlers[k]();localStorage.setItem('aii-last-view',k)},0));});}
  document.addEventListener('DOMContentLoaded',()=>{bind();const last=localStorage.getItem('aii-last-view');if(handlers[last])setTimeout(()=>handlers[last](),60);new MutationObserver(bind).observe(document.querySelector('.nav'),{childList:true,subtree:true});});
})();