(() => {
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const content=()=>document.getElementById('content');
  const setHead=(title,sub)=>{const t=document.getElementById('pageTitle'),s=document.getElementById('pageSubtitle');if(t)t.textContent=title;if(s)s.textContent=sub};
  const toast=t=>window.showToast?window.showToast(t):alert(t);
  const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};

  const style=document.createElement('style');
  style.textContent=`
    .gen-shell{display:grid;grid-template-columns:minmax(320px,.9fr) minmax(360px,1.1fr);gap:14px}.gen-card{background:#fff;border:1px solid #e8eaf1;border-radius:14px;padding:16px}.gen-card h3{margin:0 0 12px}.gen-form{display:grid;gap:10px}.gen-form label{display:grid;gap:5px;font-size:8px;color:#747b88;font-weight:700}.gen-form input,.gen-form textarea,.gen-form select{width:100%;box-sizing:border-box;border:1px solid #dfe2eb;border-radius:10px;padding:10px 11px;background:#fbfbfd;font:inherit;color:#242833}.gen-form textarea{min-height:100px;resize:vertical}.gen-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.gen-output{min-height:280px;border:1px dashed #d9ddea;border-radius:12px;background:#fafafe;padding:14px;overflow:auto}.gen-output pre{white-space:pre-wrap;font:inherit;line-height:1.55;margin:0}.gen-preview{aspect-ratio:4/5;border-radius:14px;overflow:hidden;border:1px solid #e3e5ed;background:#f3f1fb;display:grid;place-items:center}.gen-preview img{width:100%;height:100%;object-fit:cover}.gen-note{font-size:8px;color:#7d8491;line-height:1.5;margin-top:9px}.gen-badge{display:inline-flex;padding:4px 7px;border-radius:999px;background:#f1edff;color:#6647da;font-size:7px;font-weight:800;margin-bottom:10px}.gen-history{display:grid;gap:7px;margin-top:10px}.gen-history button{border:1px solid #e6e8ef;background:#fff;border-radius:9px;padding:8px;text-align:left;font-size:8px;cursor:pointer}.gen-history button:hover{border-color:#cfc5fa}.gen-two{display:grid;grid-template-columns:1fr 1fr;gap:8px}@media(max-width:900px){.gen-shell,.gen-two{grid-template-columns:1fr}}
  `;document.head.appendChild(style);

  function makeSvgPreview(prompt,format='4:5'){
    const ratio=format==='9:16'?[720,1280]:format==='1:1'?[900,900]:[900,1125];
    const safe=esc(prompt).slice(0,180);
    const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${ratio[0]}" height="${ratio[1]}" viewBox="0 0 ${ratio[0]} ${ratio[1]}"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#171925"/><stop offset=".55" stop-color="#6d4be8"/><stop offset="1" stop-color="#d7ccff"/></linearGradient></defs><rect width="100%" height="100%" fill="url(#g)"/><circle cx="75%" cy="20%" r="150" fill="rgba(255,255,255,.12)"/><circle cx="20%" cy="78%" r="210" fill="rgba(255,255,255,.08)"/><text x="7%" y="13%" fill="white" font-size="28" font-family="Arial" font-weight="700">AI INFLUENCER STUDIO</text><foreignObject x="7%" y="35%" width="86%" height="45%"><div xmlns="http://www.w3.org/1999/xhtml" style="font:700 34px Arial;color:white;line-height:1.25">${safe}</div></foreignObject><text x="7%" y="91%" fill="white" opacity=".8" font-size="22" font-family="Arial">LOCAL PREVIEW • podłącz backend AI dla finalnego zdjęcia</text></svg>`;
    return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);
  }

  function photoGenerator(){
    setHead('Generator zdjęć','Twórz brief, prompt i podgląd sesji.');
    const history=read('aii-photo-history',[]);
    content().innerHTML=`<section class="creator-tool-hero"><div><div class="eyebrow">VISUAL LAB</div><h2>Generator zdjęć</h2><p>Generator działa lokalnie od razu; finalne zdjęcia AI wymagają bezpiecznego backendu.</p></div><span class="tag">AKTYWNY</span></section><section class="gen-shell"><div class="gen-card"><span class="gen-badge">BRIEF</span><div class="gen-form"><label>Opis zdjęcia<textarea id="gPhotoPrompt" placeholder="Np. elegancka sesja beauty, jasne studio, produkt w dłoni, premium editorial..."></textarea></label><div class="gen-two"><label>Format<select id="gPhotoFormat"><option>4:5</option><option>9:16</option><option>1:1</option></select></label><label>Styl<select id="gPhotoStyle"><option>Beauty premium</option><option>Lifestyle natural</option><option>UGC</option><option>Editorial</option></select></label></div><label>Detale / produkt<input id="gPhotoDetails" placeholder="Kolory, produkt, światło, tło..." /></label></div><div class="gen-actions"><button class="primary" id="gPhotoGenerate">Generuj podgląd</button><button class="ghost" id="gPhotoCopy">Kopiuj prompt</button></div><div class="gen-note">Nie umieszczamy klucza API w kodzie GitHub Pages. Dzięki temu klucz nie wycieknie publicznie.</div></div><div class="gen-card"><span class="gen-badge">WYNIK</span><div id="gPhotoPreview" class="gen-preview"><span>Podgląd pojawi się tutaj</span></div><div id="gPhotoResult" class="gen-output" style="min-height:auto;margin-top:10px"><pre>Wpisz opis i kliknij „Generuj podgląd”.</pre></div><div class="gen-history" id="gPhotoHistory">${history.slice(0,4).map((h,i)=>`<button data-h="${i}">${esc(h.prompt)}</button>`).join('')}</div></div></section>`;
    const buildPrompt=()=>{const p=document.getElementById('gPhotoPrompt').value.trim(),f=document.getElementById('gPhotoFormat').value,st=document.getElementById('gPhotoStyle').value,d=document.getElementById('gPhotoDetails').value.trim();return `${p||'Profesjonalna sesja influencera AI'}. Styl: ${st}. Format: ${f}. ${d?`Detale: ${d}.`:''} Realistyczne światło, spójna anatomia, naturalna skóra, kompozycja reklamowa, bez znaków wodnych.`};
    document.getElementById('gPhotoGenerate').onclick=()=>{const prompt=buildPrompt();const format=document.getElementById('gPhotoFormat').value;document.getElementById('gPhotoPreview').innerHTML=`<img alt="Podgląd lokalny" src="${makeSvgPreview(prompt,format)}">`;document.getElementById('gPhotoResult').innerHTML=`<pre>${esc(prompt)}</pre>`;const h=read('aii-photo-history',[]);h.unshift({prompt,format,ts:Date.now()});save('aii-photo-history',h.slice(0,20));toast('Podgląd i prompt wygenerowane')};
    document.getElementById('gPhotoCopy').onclick=async()=>{const p=buildPrompt();try{await navigator.clipboard.writeText(p);toast('Prompt skopiowany')}catch{toast('Nie udało się skopiować')}};
    document.querySelectorAll('[data-h]').forEach(b=>b.onclick=()=>{const h=history[Number(b.dataset.h)];if(h){document.getElementById('gPhotoPrompt').value=h.prompt;toast('Wczytano wcześniejszy prompt')}});
  }

  function postGenerator(){
    setHead('Generator postów','Twórz gotowe teksty, CTA i hashtagi.');
    content().innerHTML=`<section class="creator-tool-hero"><div><div class="eyebrow">COPY LAB</div><h2>Generator postów</h2><p>Gotowy tekst do publikacji bez zewnętrznego API.</p></div><span class="tag">LOCAL AI FALLBACK</span></section><section class="gen-shell"><div class="gen-card"><div class="gen-form"><label>Temat<textarea id="gPostTopic" placeholder="O czym ma być post?"></textarea></label><div class="gen-two"><label>Platforma<select id="gPostPlatform"><option>Instagram</option><option>TikTok</option><option>Facebook</option></select></label><label>Ton<select id="gPostTone"><option>Naturalny</option><option>Ekspercki</option><option>Humorystyczny</option><option>Sprzedażowy</option></select></label></div></div><div class="gen-actions"><button class="primary" id="gPostGenerate">Generuj post</button><button class="ghost" id="gPostCopy">Kopiuj</button></div></div><div class="gen-card"><div class="gen-output"><pre id="gPostOut">Wynik pojawi się tutaj.</pre></div></div></section>`;
    let last='';document.getElementById('gPostGenerate').onclick=()=>{const topic=document.getElementById('gPostTopic').value.trim()||'dzisiejszy temat';const platform=document.getElementById('gPostPlatform').value;const tone=document.getElementById('gPostTone').value;last=`HOOK: Zatrzymaj się na chwilę — ${topic}.\n\n${tone==='Ekspercki'?'Najważniejsze jest to, żeby podejść do tematu konkretnie i bez zbędnych komplikacji.':tone==='Humorystyczny'?'Kto też miał dokładnie tak samo? 😄':'Dzisiaj pokazuję Ci mój sposób na '+topic+'.'}\n\n3 rzeczy, które warto zapamiętać:\n1. Zacznij od prostego kroku.\n2. Sprawdź, co działa u Ciebie.\n3. Zapisz efekt i poprawiaj kolejną wersję.\n\nCTA: Napisz w komentarzu, czy chcesz część 2.\n\n#creator #${platform.toLowerCase()} #content #socialmedia #inspiracja`;document.getElementById('gPostOut').textContent=last;toast('Post wygenerowany')};document.getElementById('gPostCopy').onclick=async()=>{if(!last)document.getElementById('gPostGenerate').click();try{await navigator.clipboard.writeText(last);toast('Post skopiowany')}catch{}};
  }

  function reelsGenerator(){
    setHead('Generator Reels','Hook, scenariusz, ujęcia i CTA.');
    content().innerHTML=`<section class="creator-tool-hero"><div><div class="eyebrow">SHORT VIDEO ENGINE</div><h2>Generator Reels</h2><p>Tworzy kompletny storyboard krótkiego filmu.</p></div><span class="tag">AKTYWNY</span></section><section class="gen-shell"><div class="gen-card"><div class="gen-form"><label>Temat<textarea id="gReelTopic" placeholder="Np. test kosmetyku, unboxing, recenzja..."></textarea></label><div class="gen-two"><label>Długość<select id="gReelLen"><option>15 s</option><option>30 s</option><option>45 s</option><option>60 s</option></select></label><label>Cel<select id="gReelGoal"><option>Zaangażowanie</option><option>Sprzedaż</option><option>UGC</option><option>Recenzja</option></select></label></div></div><div class="gen-actions"><button class="primary" id="gReelGenerate">Generuj Reels</button></div></div><div class="gen-card"><div class="gen-output"><pre id="gReelOut">Storyboard pojawi się tutaj.</pre></div></div></section>`;
    document.getElementById('gReelGenerate').onclick=()=>{const t=document.getElementById('gReelTopic').value.trim()||'wybrany produkt';const len=document.getElementById('gReelLen').value;const goal=document.getElementById('gReelGoal').value;document.getElementById('gReelOut').textContent=`REELS • ${len} • ${goal}\n\n0–3 s — HOOK\n„Nie spodziewałam się, że ${t} zrobi aż taką różnicę.”\n\n3–7 s — UJĘCIE 1\nClose-up produktu / detalu.\n\n7–12 s — UJĘCIE 2\nPokaż użycie i jeden konkretny benefit.\n\n12–15 s — CTA\n„Zapisać Wam pełną recenzję?”\n\nNAPIS NA EKRANIE\n${t}\n\nMONTAŻ\nSzybkie cięcia, napisy zsynchronizowane z ujęciami, bez długiego intro.`;toast('Storyboard wygenerowany')};
  }

  function ideasGenerator(){
    setHead('Pomysły na treści','Szybki bank pomysłów na publikacje.');
    content().innerHTML=`<section class="creator-tool-hero"><div><div class="eyebrow">IDEA ENGINE</div><h2>Pomysły na treści</h2><p>Generuj serię tematów pod wybraną niszę.</p></div></section><section class="gen-card"><div class="gen-form"><label>Nisza / temat<input id="gIdeaTopic" placeholder="beauty, książki, lifestyle..." /></label></div><div class="gen-actions"><button class="primary" id="gIdeaGenerate">Generuj 10 pomysłów</button></div><div class="gen-output" style="margin-top:12px"><pre id="gIdeaOut">Pomysły pojawią się tutaj.</pre></div></section>`;document.getElementById('gIdeaGenerate').onclick=()=>{const t=document.getElementById('gIdeaTopic').value.trim()||'Twoja nisza';document.getElementById('gIdeaOut').textContent=[`3 błędy w ${t}, które popełnia większość osób`,`Mój najprostszy trik związany z ${t}`,`Test: czy droższe naprawdę znaczy lepsze?`,`5 rzeczy, których nie kupiłabym ponownie`,`Przed i po — bez upiększania wyniku`,`Ranking TOP 5 tego miesiąca`,`Co wybrać przy małym budżecie?`,`Mit vs fakt: ${t}`,`Kulisy: jak naprawdę wygląda przygotowanie materiału`,`Q&A: odpowiadam na najczęstsze pytania`].map((x,i)=>`${i+1}. ${x}`).join('\n');toast('Pomysły wygenerowane')};
  }

  function campaignsGenerator(){
    setHead('Kreator kampanii','Brief, harmonogram i materiały kampanii.');
    content().innerHTML=`<section class="creator-tool-hero"><div><div class="eyebrow">CAMPAIGN BUILDER</div><h2>Kreator kampanii</h2><p>Buduje gotowy plan kampanii od briefu do publikacji.</p></div></section><section class="gen-shell"><div class="gen-card"><div class="gen-form"><label>Marka / produkt<input id="gCampBrand" placeholder="Nazwa marki lub produktu" /></label><label>Cel kampanii<select id="gCampGoal"><option>Świadomość</option><option>Sprzedaż</option><option>UGC</option><option>Premiera</option></select></label><label>Wymagania<textarea id="gCampReq" placeholder="Formaty, claimy, deadline, obowiązkowe ujęcia..."></textarea></label></div><div class="gen-actions"><button class="primary" id="gCampGenerate">Utwórz plan</button></div></div><div class="gen-card"><div class="gen-output"><pre id="gCampOut">Plan kampanii pojawi się tutaj.</pre></div></div></section>`;document.getElementById('gCampGenerate').onclick=()=>{const b=document.getElementById('gCampBrand').value.trim()||'Marka';const g=document.getElementById('gCampGoal').value;const r=document.getElementById('gCampReq').value.trim();document.getElementById('gCampOut').textContent=`KAMPANIA: ${b}\nCEL: ${g}\n\n1. BRIEF\n${r||'Ustalić key message, obowiązkowe elementy i zakazane sformułowania.'}\n\n2. PRODUKCJA\n• 1 Reels\n• 3 Stories\n• 3 zdjęcia pionowe\n\n3. AKCEPTACJA\nWersja robocza → poprawki → final.\n\n4. PUBLIKACJA\nReels + Stories tego samego dnia.\n\n5. RAPORT\nZasięg, wyświetlenia, kliknięcia, zapisania, komentarze.`;toast('Plan kampanii utworzony')};
  }

  const handlers={images:photoGenerator,'image-generator':photoGenerator,posts:postGenerator,reels:reelsGenerator,'reels-generator':reelsGenerator,ideas:ideasGenerator,campaigns:campaignsGenerator};
  function bind(){document.querySelectorAll('.nav-item[data-view]').forEach(a=>{const key=a.dataset.view;if(!handlers[key]||a.dataset.genBound)return;a.dataset.genBound='1';a.addEventListener('click',()=>setTimeout(()=>{handlers[key]();localStorage.setItem('aii-last-view',key)},0));});}
  document.addEventListener('DOMContentLoaded',()=>{bind();const last=localStorage.getItem('aii-last-view');if(handlers[last])setTimeout(()=>handlers[last](),30);new MutationObserver(bind).observe(document.querySelector('.nav'),{childList:true,subtree:true});});
})();